# Site settings
# in the templates available like {{ site.myvariable }}.
title: Portfolio
email: your-email@domain.com
brand: Alex Andreasen
headline: Developer, avid reader and life improver
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aa-pastprojects.github.io/AA-PastProjects/" # the base hostname & protocol for your site
copyright: 2018 Alex Andreasen

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: your.name@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

